sudo: required
services:
  - docker

before_install:
  - docker build -t alexiscl/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexiscl/react-test npm test

after_success:
  - docker build -t alexiscl/multi-client ./client
  - docker build -t alexiscl/multi-nginx ./nginx
  - docker build -t alexiscl/multi-server ./server
  - docker build -t alexiscl/multi-worker ./worker
  # login to the docker cli
  - echo "$DOCKER_PW" | docker login  -u "$DOCKER_ID" --password-stdin
  # take those images and push to docker hub
  - docker push alexiscl/multi-client
  - docker push alexiscl/multi-nginx
  - docker push alexiscl/multi-server
  - docker push alexiscl/multi-worker
  
deploy: 
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-3-486833496224
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY